### ISSUE TITLE
Filebot not being detected properly.

### ISSUE THREAD

**Issue by Nedlinin** [Laharah/deluge-FileBotTool#1]
Addon is installed and enabled. Right click menu works but when the dialog comes up it states that Filebot is not found.  However, FileBot is, in fact, installed.

Windows 10 x64.  Deluge 1.3.11. FileBotTool Beta 0.8.3.

**Comment by Laharah** [comment]
@Nedlinin 
Have you tried restarting deluge after everything is installed?

if it doesn't have an effect, could you try opening a command prompt and typing `filebot -version`? And tell me what comes up? Also, could you tell me where filebot is installed to?

**Comment by Nedlinin** [comment]
I have restarted Deluge and no luck.

I should mention I'm running the daemon and using the thin client.  Not sure how much of a difference it'll make.

    C:\Users\nedlinin>filebot -version
    FileBot 4.6.1 (r3315) / Java(TM) SE Runtime Environment 1.8.0_73

Install location:

    C:\Program Files\FileBot

**Comment by Nedlinin** [comment]
OK. Got it figured out.

Because I am running the thin client I have to make sure Filebot is installed and in the path of the machine I am connecting to :)

In my case it was installed but for some reason it was not in the path variable.  I added it into the path on that box and it started to detect it properly.

**Comment by Laharah** [comment]
@Nedlinin 

glad you got it figured out, I'll add something to the instructions to clarify that FileBot has to be on the path of the server machine.

**Comment by jonyskids** [comment]
How does one determine, "the path variable of the server machine"? I am runing headless server on dietpi.

Thanks,
Jon

**Comment by Laharah** [comment]
@jonyskids the path variable is a variable that has a list of paths the OS checks when asked to run a command: https://en.wikipedia.org/wiki/PATH_(variable)

You have to should make sure that wherever the filebot.exe is located, is in the path variable.

Almost every unix system uses $PATH as the path variable. To check what's in yours try running `echo $PATH` in a command prompt connected to your server. 

If you need to add a path to your path variable, you generally add a line like `export PATH=/path/to/filebot/folder:$PATH` to your `~/.bashrc` file or '~/.profile`

see here for more info: https://www.cyberciti.biz/faq/how-to-add-to-bash-path-permanently-on-linux/

FilebotTool should be manually checking the usual install locations for the filebot.exe so if you're still having trouble feel free to open a new issue and I can try and help troubleshoot with you.
