### ISSUE TITLE
Deluge 1.3.12 FileBot Not Found

### ISSUE THREAD

**Issue by JohnnyT009** [Laharah/deluge-FileBotTool#11]
I am using the 2.6  egg and when I right click a download to test it tells me that FileBot Not Found. I have it installed and working. Is it looking for it in a specific place? Thanks

**Comment by JohnnyT009** [comment]
As a note when I am in cmd line if I type filebot it does run filebot so it seems to be a working parameter.

**Comment by Laharah** [comment]
Are you running deluge in client-server mode, or is everything running on one machine?

**Comment by JohnnyT009** [comment]
It is all on one machine.

**Comment by Laharah** [comment]
Have you tried restarting? sometimes path variables don't get correctly refreshed for running processes.

**Comment by JohnnyT009** [comment]
I will restart the whole PC quick and let you know. Thanks for the quick response.

**Comment by JohnnyT009** [comment]
Still getting the same error after a reboot. I believe I have filebot 64bit , does that matter?

**Comment by Laharah** [comment]
it shouldn't, what OS are you using?

**Comment by JohnnyT009** [comment]
Windows 10 Pro x64

**Comment by Laharah** [comment]
is filebot installed to `C:\Program Files\FileBot\filebot.exe`?

**Comment by JohnnyT009** [comment]
Yes, C:\Program Files\FileBot

and filebot.exe is in there along with all the other files.

**Comment by Laharah** [comment]
well, the plugin checks that location even if filebot isn't in the path variable, so it should be showing up. under preferences -> interface, is the `classic mode` checkbox checked?

**Comment by JohnnyT009** [comment]
Yes it is checked in Deluge preferences.

**Comment by Laharah** [comment]
... hmm. This is a weird one. What happens if you type `filebot -version` into a cmd window?

**Comment by JohnnyT009** [comment]
filebot pops up quick and disappears.

**Comment by Laharah** [comment]
does any text show up in the cmd window? And you typed `filebot -version` exactly? There should have been some text like `FileBot 4.7.2 (r4178) / Java(TM) SE Runtime Environment 1.8.0_92`

**Comment by JohnnyT009** [comment]
I updated my comment, I was not running cmd as admin.

**Comment by Laharah** [comment]
ah, I think I see the problem. Try closing deluge and re-launching it with "run as admin" in the right click menu. If the plugin works, then it's a permissions issue.

**Comment by JohnnyT009** [comment]
Well SHUT MY MOUTH, that fixed it :-) thanks a ton I am excited to use this.

**Comment by Laharah** [comment]
no problem, if you don't want to keep using run as administrator, make sure that `filebot -version

**Comment by Laharah** [comment]
No problem, glad we figured it out. If you don't want to keep running deluge as admin, make sure you can run `filebot -version` from non-administer programs. You should be able to change the permissions in the security settings on filebot.exe so that deluge will be able to run it.
