### ISSUE TITLE
Explanation of Linking - Keep Seeding Move File

### ISSUE THREAD

**Issue by JohnnyT009** [Laharah/deluge-FileBotTool#12]
I would email you directly but I thought this might be useful for other users.
How do you move a torrent after it is done and renamed but keep it seeding? I would like the finished torrent moved to its final destination and be renamed but have it still be seedable. This way I never have two copies of the same file. Is this even possible with filebot and your plugin? I am pretty new to this so maybe I am just totally missing something. Thanks

**Comment by Laharah** [comment]
No problem. That's actually why I wrote this plugin. No matter what settings you use, the torrent will keep seeding correctly. The default `move` behavior moves and renames the torrent and keeps it seeding without any additional copies.

**Comment by JohnnyT009** [comment]
Excellent, I will give that a go. Thank you,
