### ISSUE TITLE
Auto execute rule not working 

### ISSUE THREAD

**Issue by godloth** [Laharah/deluge-FileBotTool#21]
Hello there, 

i've been playing around with the autoexecute function of filebottool without too much success.
It works perfectly when manually kicked but it's not trapping anything either using the label or tracker field

ie: i have a torrent :
![2016-12-30 11-50-08](https://cloud.githubusercontent.com/assets/22320005/21568903/38806a72-ce86-11e6-8f3a-688aa7a027f1.jpg)

then i've tried those rules in order 

![2016-12-30 11-51-30](https://cloud.githubusercontent.com/assets/22320005/21568923/5b14ed4c-ce86-11e6-8724-a63a2d893180.jpg)

i've tried many settings with no success , but again , when i launch filebottool manually select the TV shows profile it works great .

any help would be apprectiated 

( running on Raspbian jessie, using filebot 4.7.5 )

**Comment by Laharah** [comment]
Well, I'm not sure what the tracker URL is on that torrent, but it looks like you're trying to match the 's0' part of 'S0E11'? If that's the case, you want to use the `file path' field matching, which uses the file names to do its matching. looking at your rules, it's unlikely that either the label or the tracker url will have 'S0' in them on that torrent. 

You should also be aware that each new torrent is run through the auto execute rules exactly once, at the moment it finishes downloading. So it's best to use the tracker URL or automatically applied labels from either the deluge label plugin/labelplus to do the sorting on. Any torrent that autoexecute didn't match against will have to be manually sorted. Currently there's no way to manually execute the auto execute rules except for re-downloading. I may have to add an ability to do that in a future update.

**Comment by godloth** [comment]
Thanks a bunch I thought the label option was looking at the file name 

I'll look into it later on when I'm back at home 

Thanks a bunch
