### ISSUE TITLE
Install deluge filebot tool on raspberry pi

### ISSUE THREAD

**Issue by therudy** [Laharah/deluge-FileBotTool#23]
Hello

i'm using deluge rpi

when i try to use filebot tool i get

[ERROR   ] 20:05:23 rpcserver:304 Exception calling RPC request: 'CorePlugin.Fil                                                   eBotTool'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/co                                                   re/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/co                                                   re/core.py", line 538, in enable_plugin
    self.pluginmanager.enable_plugin(plugin)
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/co                                                   re/pluginmanager.py", line 82, in enable_plugin
    super(PluginManager, self).enable_plugin(name)
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/pl                                                   uginmanagerbase.py", line 151, in enable_plugin
    component.start([instance.plugin._component_name])
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/co                                                   mponent.py", line 290, in start
    if self.components[name]._component_depend:
KeyError: 'CorePlugin.FileBotTool'

any idea ?

thank

**Comment by Laharah** [comment]
it looks like the filebot tool plugin isn't installed on the raspberry pi's installation of deluge. Try uninstalling the plugin. Then connect to the raspberry pi, and re-install the plugin. It should be added correctly to the pi. If not you can manually place the 2.7.egg file in ~/.config/deluge/plugins folder. 

Once that is done make sure that you have filebot installed and runnable on your raspberry pi. @rednoah recommends that you use the portable version of filebot on embeded systems

something like 
`sudo wget -0 filebot.tar.xz 'https://app.filebot.net/download.php?type=portable&version=4.7.7'`

`sudo tar -xvf filebot.tar.xz`

should download and extract it. Then be sure to symlink `filebot.sh` to `/usr/bin` so that deluge can run it.

something like `sudo ln -s filebot.sh /usr/bin/filebot` would do that.

If you run into trouble check out the [wiki](https://github.com/Laharah/deluge-FileBotTool/wiki) or report back here and I'll see if I can help.

**Comment by therudy** [comment]
Hello,
thank for your reply

sorry for my english i'm french

i have already added 

pi@raspberrypi:~/.config/deluge/plugins $ ls
FileBotTool-1.1.4-py2.7.egg


manually because its doesnt put with automatique add

does it right ?

i try to reinstall filebot, and i contact you on a few of minuts, thank

**Comment by rednoah** [comment]
Here's a script for installing FileBot manually:
https://github.com/filebot/plugins/blob/master/bash/install-filebot.sh

**Comment by therudy** [comment]
sudo sh script.sh

sudo tar -xvf FileBot_4.7.7-portable.tar.xz

sudo ln -s FileBot.jar /usr/bin/filebot 

the script doesnt give me a .sh but a .jar ?

and when i type "filebot" nobody launch

sorry i'm really not good in linux ^^'

**Comment by therudy** [comment]
Hello

thank for your reply ! :) its super cool

sorry i'm french

when i run the rednoah script


pi@raspberrypi:~ $ sudo ./script.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 15403    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0 15390    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0   477    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0   391    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100 17.3M  100 17.3M    0     0   114k      0  0:02:34  0:02:34 --:--:--  482k
FileBot_4.7.7-portable.tar.xz: Réussi
FileBot.jar
filebot.cmd
filebot.portable.launcher.exe
filebot.portable.launcher.l4j.ini
filebot.sh
update-filebot.sh


/usr/bin/ get filebot

but when i type filebot its doesnt run ?

but when i sudo ./filebot.sh from source its work :s 

sorry i'm not good in linux

**Comment by Laharah** [comment]
Make sure that filebot is in `/usr/local/bin/` or in `/usr/bin` and that both are in your $PATH variable. (`echo $PATH` should have `/usr/local/bin` and `/usr/bin` in it). You should also try restarting just in case. 

It could also be permissions. Does `sudo filebot -version` work? If yes, use `sudo chmod 755 filebot.sh`

Are you connecting to deluge on the raspberry pi from another computer, or are you doing it directly? If you go to deluge > preferences > Interface > Classic Mode, make sure that the box is not checked, and that you are connecting to the raspberry pi under the Connection Manager.

Also make sure that the deluged server is running on the pi:

`ps aux | grep deluged`

**Comment by therudy** [comment]
Hello

thank for your reply :)

my /home/pi/filebot ls get


data                           filebot.cmd  filebot.portable.launcher.exe      filebot.sh  update-filebot.sh
FileBot_4.7.7-portable.tar.xz  FileBot.jar  filebot.portable.launcher.l4j.ini  script.sh

my

/usr/bin get filebot

Path variable give me : 

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

and


pi@raspberrypi:~/filebot $ sudo filebot -version
FileBot 4.7.7 (r4678) / Java(TM) SE Runtime Environment 1.8.0-ea / Linux 4.4.38-v7+ (arm)

chmod 755 dont change problem


pi@raspberrypi:~/filebot $ filebot
-bash: /usr/bin/filebot: Aucun fichier ou dossier de ce type

my interface deluge : https://image.noelshack.com/fichiers/2017/06/1486472067-lui.png

and yes i connect to another computer, from external ip, but deluged and deluge-web is launched


pi@raspberrypi:~/filebot $ ps aux | grep deluged
root       764  9.7  4.2  81296 42144 ?        Sl   10:52  11:55 /usr/bin/python /usr/local/bin/deluged stop
pi        3995  0.0  0.1   4536  1848 pts/0    S+   12:54   0:00 grep --color=auto deluged


thank for your help :)

if u need i can give you ssh access and same for deluge gui

**Comment by therudy** [comment]
Same problem :(

spi@raspberrypi:~ $ sudo deluged
pi@raspberrypi:~ $ [ERROR   ] 13:01:35 torrentmanager:1146 on_alert_fastresume_rejected: Dragon Ball Saison 1 Truefrench DVDrip x264 AAC SBZ fast resume rejected: missing or invalid 'file sizes' entry
[ERROR   ] 13:02:14 rpcserver:304 Exception calling RPC request: 'CorePlugin.FileBotTool'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/core/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/core/core.py", line 538, in enable_plugin
    self.pluginmanager.enable_plugin(plugin)
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/core/pluginmanager.py", line 82, in enable_plugin
    super(PluginManager, self).enable_plugin(name)
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/pluginmanagerbase.py", line 151, in enable_plugin
    component.start([instance.plugin._component_name])
  File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.13-py2.7.egg/deluge/component.py", line 290, in start
    if self.components[name]._component_depend:
KeyError: 'CorePlugin.FileBotTool'

**Comment by Laharah** [comment]
Ah, I see the problem. You are using the webui. FileBotTool only works with the deluge client.

download and install deluge on your windows computer:
http://dev.deluge-torrent.org/wiki/Download

Then follow the instructions here:
http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient#GTKUI

**Comment by therudy** [comment]
AAAAh, sorry for my noob attitude,

and thank you :) i try this night i'm not at my home

have a good day

**Comment by Laharah** [comment]
No problem, let me know if you get it working :)

**Comment by therudy** [comment]
Sorry but on deluge exe, i put the external ip, what port i need to use ? my ssh is 3387 and deluge is 8112, and with port bydefault nobody works :x

**Comment by Laharah** [comment]
You have to make sure that "allow remote connections" is on and that the port matches up. If you load up the webUI you can see your settings in preferences > Daemon. Mine looks like this:

![WebUI Deamon Config](http://i.imgur.com/MUXdlx7.png)

Make sure allow remote connections is checked, and use the port that is listed there.

**Comment by therudy** [comment]
thank for your reply

already checked :(

strange,i will search

**Comment by Laharah** [comment]
You should double check the instructions for setting up the thinclient here from the top, to make sure everything is configured correctly:
http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

Make sure that the authentication file has the right user and password, etc.

**Comment by therudy** [comment]
thank

i think problem is from

-
Failed to connect to 127.0.0.1:58846 with reason: Username does not exist

my auth get  pi:password:10

hmm

**Comment by Laharah** [comment]
make sure that on your windows deluge you're using the IP of the raspberry pi, and not localhost

**Comment by therudy** [comment]
Yeah sure i use 192.168.1.2 its the local ip

tried with internet ip but same problem

i'm going to abandon, sorry for the time wasted

**Comment by therudy** [comment]
ok its worked, sorry, i will try filebot gui !

**Comment by therudy** [comment]
Just, how can i delete filetool gui to reinstall it ? x') thank

**Comment by Laharah** [comment]
just so long as it's installed on windows and on the raspberry pi, it should work ok. Just follow the instructions [here](https://github.com/Laharah/deluge-FileBotTool/wiki/Installation)

**Comment by therudy** [comment]
Thank for your reply

https://image.noelshack.com/fichiers/2017/06/1486501211-sans-titre.png

doesnt understand what i'm doing wrong ^^''

i have put .egg on webgui and from windows

**Comment by therudy** [comment]
Ok its work ! woow, sorry i'm really a big noob,

and thank a lot for your help ! :)

**Comment by Laharah** [comment]
glad you got it working!
