### ISSUE TITLE
Possible to get multiple issue of movie?

### ISSUE THREAD

**Issue by therudy** [Laharah/deluge-FileBotTool#24]
Hello

a small question

i try to rename the manga "dragon ball", not dragon ball z, not dragon ball super, not the movie

just 

https://www.themoviedb.org/tv/12609-dragon-ball

dragon ball similar as themoviedb

https://image.noelshack.com/fichiers/2017/06/1486551786-sans-titre.png

i put dragon ball, themoviedb , and its dont find the good

on the real filebot executable gui i can choose différents dragon ball

does it possible with filebottool gui ?

sorry for my english

and thank for your reply :)

**Comment by Laharah** [comment]
Not really. TheMovieDB is more for movies than tv shows so it thinks you have one movie broken over 22 parts. You should use thetvdb database instead.

**Comment by therudy** [comment]
Hello,

thank for your reply

same problem with thetvdb and other :(

i think im going to use manually filebot for manga but filetool for movie, the moviedb get french metadata for my plex

**Comment by Laharah** [comment]
That's strange. My test seems to work:

![screen shot 2017-02-08 at 3 59 06 am](https://cloud.githubusercontent.com/assets/539998/22736461/17f5e394-edb3-11e6-9dbb-ebe262e44855.png)

Sorry that it's giving you problems.

**Comment by therudy** [comment]
thank for your reply

i re-launch the search for thetvdb

https://image.noelshack.com/fichiers/2017/06/1486555611-sans-titre.png

its take many time for rpi, probably the processor who is not really powerfull

i reply when i'ts ok,

thank :)

**Comment by therudy** [comment]
Hello,

tried 3 times

i have problem ^^'

https://image.noelshack.com/fichiers/2017/06/1486629068-sans-titre.png

sorry and thank for your help ! :)

**Comment by Laharah** [comment]
Does the error happen every time you try the dry-run? Can you post the exact settings you used?

**Comment by therudy** [comment]
Thank for your reply

only with tvdb hmm,

works fine with anidb

**Comment by Laharah** [comment]
if you can still get those logs I'd like to see them. It may be an issue with filebot itself.

**Comment by therudy** [comment]
sorry about this but where can i get the logs about this?x')

**Comment by Laharah** [comment]
if you stop the deluged service on your raspberry pi and then restart it with these flags:

`sudo deluged -L DEBUG -l ~/deluged_log.txt`

that will save the debug data to ~/deluged_log.txt

**Comment by therudy** [comment]
thank for your reply,

i cant do this now because a renaming process is during for many manga

when its ok it try it and post here the log

thank

**Comment by therudy** [comment]
Hmm, look like works now, but {plex} dont get real good architectory for plex, its strange, but i close the thread, thank you for your help
