### ISSUE TITLE
Error on renaming

### ISSUE THREAD

**Issue by therudy** [Laharah/deluge-FileBotTool#27]
https://image.noelshack.com/fichiers/2017/09/1488444780-567.png

https://image.noelshack.com/fichiers/2017/09/1488444776-123.png

Hello, small problem when i try to rename a movie :-)

i think the problem is the "ûlé" on the name ?

any idea ?

thank you :)

**Comment by Laharah** [comment]
Filebot says that it can't find the file to rename it. I think the problem might be the brackets ("[" "]"). Try removing them and trying again. Also use ssh to make sure that the file is titled what deluge thinks it is, and that it's in the right place.

**Comment by therudy** [comment]
Hello,

Thank for your help,

and its solved, idk why but the filebot have been removed/renaming the movie and not changing the name on deluge

but ok its solved

thank you :)
