### ISSUE TITLE
Plugin enabled, but no menu items

### ISSUE THREAD

**Issue by markcs** [Laharah/deluge-FileBotTool#29]
HI!

I use deluged and deluge-web.

I have FileBotTool 1.1.5 enabled via the web plugins , but I do not see any menu items when I right click on a torrent or in the Preferences menu list.

I have put both FileBotTool-1.1.5-py2.7.egg and FileBotTool-1.1.5-py2.6.egg in the plugins folder.

I see this in the debug log for the deluge-web when I try to enable FileBotTool:
[ERROR   ] 21:51:06 client:391 RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.enable_plugin(FileBotTool)
--------------------------------------------------------------------------------
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 299, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/deluge/core/core.py", line 524, in enable_plugin
    self.pluginmanager.enable_plugin(plugin)
  File "/usr/lib/python2.7/dist-packages/deluge/core/pluginmanager.py", line 82, in enable_plugin
    super(PluginManager, self).enable_plugin(name)
  File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 151, in enable_plugin
    component.start([instance.plugin._component_name])
  File "/usr/lib/python2.7/dist-packages/deluge/component.py", line 290, in start
    if self.components[name]._component_depend:

KeyError: CorePlugin.FileBotTool

Any tips appreciated.

**Comment by Laharah** [comment]
Hi, it looks like you're trying to FileBotTool via the web IU. Unfortunately, that won't work. FileBotTool is only for the GTK UI, meaning that you will have to have deluge installed on a client machine, and access deluge through a remote connection.

You can follow the instructions on how to do that here:
http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient#GTKUI

If you have trouble connecting, look through the deluge daemon setup section, and make sure that your server is setup correctly.

**Comment by markcs** [comment]
Ah okay. Thanks, I wasn't aware this plugin didn't work through the WebUi.

This issue can be closed then.

**Comment by Laharah** [comment]
No problem. I'd like to get it working through the webUI, but my javascript is pretty bad and It'd be a pretty big project, since most of the code right now is UI code.
