### ISSUE TITLE
No proper logging

### ISSUE THREAD

**Issue by jkanczler** [Laharah/deluge-FileBotTool#33]
I'm getting an error when clicking on Execute Filebot button:
```
FILEBOT OUTPUT DUMP:
 error on torrent 8877c33a6cb9201466846b3cf616f44d570b1d98:
    FILEBOT OUTPUT DUMP:
```
In the deluge log file:
`[ERROR   ] 12:21:49 common:52 [FilebotTool] FILEBOT ERRORFILEBOT OUTPUT DUMP:`

**Comment by Laharah** [comment]
Did you get the same error if you try to do a dry-run instead of execute? That logging does in fact work, it seems that FileBot didn't output anything, just raised a non-zero exit code, which is very unusual. 

Does the plugin work on any other torrents? What does the version info say at the top of the window when you try to run a rename?

**Comment by jkanczler** [comment]
I suppose it some kind of a permission denied issue. I'm working on that as I'm getting the following errors, when I'm trying to run the following script manually:

```
filebot -script fn:amc --output "/media/kodi/KanczlerShare/MediaLibrary" --def "movieFormat=Movies\{n} ({y})\{n}" --action copy -non-strict "/media/kodi/KanczlerShare/Torrent/Completed/Movies" --log-file amc.log --def excludeList=amc.txt
filebot -script fn:amc --output "/media/kodi/KanczlerShare/MediaLibrary" --def "seriesFormat=TV Shows\{n}\Season {s}\{n}.{s00e00}.{t}" --action copy -non-strict "/media/kodi/KanczlerShare/Torrent/Completed/TVShows" --log-file amc.log --def excludeList=amc.txt
```

Result:
```
Locking /home/kodi/snap/filebot/9/data/logs/amc.log
Run script [fn:amc] at [Tue Aug 01 22:20:47 CEST 2017]
Parameter: movieFormat = Movies\{n} ({y})\{n}
Parameter: excludeList = amc.txt
Argument[0]: /media/kodi/KanczlerShare/Torrent/Completed/Movies
Use excludes: /media/kodi/KanczlerShare/MediaLibrary/amc.txt
Permission denied
java.io.IOException: Permission denied
	at java_io_File$createNewFile$5.call(Unknown Source)
	at Script1.run(Script1.groovy:191)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:64)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:74)
	at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:119)
	at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
	at net.filebot.Main.main(Main.java:115)

Failure (°_°)
Locking /home/kodi/snap/filebot/9/data/logs/amc.log
Run script [fn:amc] at [Tue Aug 01 22:20:52 CEST 2017]
Parameter: seriesFormat = TV Shows\{n}\Season {s}\{n}.{s00e00}.{t}
Parameter: excludeList = amc.txt
Argument[0]: /media/kodi/KanczlerShare/Torrent/Completed/TVShows
Failed to load excludeList: java.nio.file.AccessDeniedException: /media/kodi/KanczlerShare/MediaLibrary/amc.txt
Failure (°_°)
```

**Comment by jkanczler** [comment]
Forgot to answer your question: On dry run it works, but not correctly as nothing changed and I can't see the movie in the output folder:
![image](https://user-images.githubusercontent.com/10925650/28845651-077cf00e-7709-11e7-9da8-eee4c209b5c9.png)

**Comment by Laharah** [comment]
I booted up a vm with ubuntu and downloaded FileBot with the software center and saw the same problem that you did. Turns out there's some kind of problem where the logfile filebot writes out doesn't play nice with something in ubuntu's snap tempfiles. I posted a fix in [version 1.1.10](https://github.com/Laharah/deluge-FileBotTool/releases/tag/1.1.10).

Could you download it and let me know if it works as expected?

**Comment by jkanczler** [comment]
I could see the result now from FileBot, though that's not helpful for me, but I think that's a problem of FileBot instead of your tool.

![image](https://user-images.githubusercontent.com/10925650/28858598-f919699a-7751-11e7-9122-e27c2c3fea67.png)

**Comment by Laharah** [comment]
at first glance it looks like there is a problem with the permissions on `KanczlerShare`, preventing filebot from creating the symlinks. Hope you figure out the issue, and let me know if you run into any more problems.

**Comment by jkanczler** [comment]
Thanks. I've found the problem. The problem was that I installed filebot as a snap package, and as a snap package it has different privileges. Everything works fine as I've installed filebot as a debian package onto my Ubuntu Desktop.
