### ISSUE TITLE
Filebot tasks fail

### ISSUE THREAD

**Issue by PooterTF** [Laharah/deluge-FileBotTool#35]
> FilebotRuntimeError error on torrent 4cdc60aec43c98c27999083bf297556e713e857d:
>     FILEBOT OUTPUT DUMP:
>     Rename episodes using [TheTVDB]
>     Failure (°_°)
> 

This occurs whenever a Filebot task is attempted through FilebotTool.  No matter what database is attempting to rename, etc.  Filebot runs fine manually on the same exact file, but any jobs sent through FilebotTool pulls this error, both in automation and in dry-run.

It's FileBot 4.7.9 (r4984) / OpenJDK Runtime Environment 1.8.0_131 / Linux 4.8.0-45-generic (amd64)

**Comment by Laharah** [comment]
hmm that's a bit weird. Does the user account / group that deluge runs on have the correct permissions to access the files you're trying to rename?

**Comment by Laharah** [comment]
For future people encountering this problem, the filebot cache files may have incorrect permissions. They are located in `~/.filebot/cache`. I've added some better error reporting which may help people identify this problem themselves.
