### ISSUE TITLE
AniDB renaming episodes titles as episode numbers

### ISSUE THREAD

**Issue by jbowwow02** [Laharah/deluge-FileBotTool#37]
When renaming a recently aired episode, the plugin renames the episode title as the episode number.

![image](https://user-images.githubusercontent.com/4137235/46997248-dfee9d00-d13c-11e8-99b5-d20d9a4ac4a1.png)

But when renaming the episode through filebot itself the episode title shows up fine.

![image](https://user-images.githubusercontent.com/4137235/46997352-162c1c80-d13d-11e8-98f0-f36eedb4c85d.png)

Only seems to happen when anidb is the selected database.

**Comment by Laharah** [comment]
I couldn't replicate this:

![screenshot](https://i.imgur.com/ENSoGmW.png)

The only differences that I noticed about your setup was 

1. It was on windows, which shouldn't matter

2. Your Filebot Version is listed as 4.8.4

I'm not entirely sure where you got that from since the newest version I could find on filebot.net is version 4.8.2

The other thing that you might try is clearing your cache. It should be located at `AppData\FileBot\Cache`. An old cache might be getting hit when you do a rename, while -list probably avoids the cache and goes to an actual lookup.

If you wanna test the actual command that Dry Run calls I believe it would be

`filebot -rename --action test --db AniDB --format '{primaryTitle} - {sxe} - {t}' --order absolute --lang en -non-strict -r "{PATH}"`. 

Maybe that will let you see the same result in filebot. Ultimately whatever filebot gives back is what the plugin renames to.

**Comment by jbowwow02** [comment]
Version 4.8.4 seems to be the version for the application on the windows store which is where I downloaded filebot from. So I just tried what you suggested with something I just downloaded 5 minutes ago. 

![image](https://user-images.githubusercontent.com/4137235/47040768-bc5f3d00-d1a4-11e8-927c-f2c1dce4500d.png)

I tried the dry run command and got this.
![image](https://user-images.githubusercontent.com/4137235/47040870-034d3280-d1a5-11e8-9230-f5b65d0ce230.png)

Rerunning the dry run in the extension after the running it in terminal gives this.
![image](https://user-images.githubusercontent.com/4137235/47041045-6dfe6e00-d1a5-11e8-8a75-cbad08ea9210.png)

As you said, it does seem to be a cache problem but what I don't understand is why doing it in filebot itself or terminal makes it rename like usual but it doesn't work for the extension when they're running the same commands.

**Comment by Laharah** [comment]
Hmm. That is weird behavior. You may have just hit a cache timing and got lucky, but it's unlikely. Is it possible you have 2 versions of FileBot installed? Check and see if running `filebot -verson` gives you the same string that at the top in the rename window.

Either way I'd recommend deleting your cache files. According to the forums the windows store version of filebot stores it's data at `%USERPROFILE%\AppData\Local\Packages\PointPlanck.FileBot_*\LocalCache\Roaming\FileBot` Just delete the cache directory and it should clear it.

**Comment by rednoah** [comment]
`FileBot 4.8.4` is indeed the Windows Store version. My first though though was caching as well.

Let's try to clear the cache and see what happens:
https://www.filebot.net/forums/viewtopic.php?f=3&t=1996

**Comment by Laharah** [comment]
I'm gonna close this issue as fixed. Feel free to re-open if you run into the same problem again.

**Comment by purposelycryptic** [comment]
Came across this in a Google search, and while I realize the issue has been marked closed for over 2 months, I just thought I'd add, for anyone running into the same issue, that this is indeed almost certainly a cache issue. AniDB has very low rate limits when it comes to pulling metadata, so a lot of data ends up being cached to avoid bans, and, additionally, sometimes what you see on the site hasn't quite propagated through the system to the point the API is pulling from, especially if you are renaming files directly after RSS release - unless someone has updated an episode name pre-release, the system default name is just "Episode _X_", and it can take a bit to update. 

I've had the same experience fairly consistently using Hama on Plex, the Anime Plugin on Emby, AniAdd, AOM, WebAOM and Shoko's renamer - frequently enough that I actually rewrote my AniAdd script to not move files to the destination folder unless all metadata values were properly available.

I'm neither a mod nor developer at AniDB, just an avid fan that tries to correct incorrect/incomplete/missing metadata on the site whenever I see it, so this explanation may not be 100% accurate, but it matches all my findings over the years. Hopefully this post isn't a bother, but every time I see a thread like this, I can't help but think of this:

![XKCD - Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
