### ISSUE TITLE
Filebot is unregistered error

### ISSUE THREAD

**Issue by jako800** [Laharah/deluge-FileBotTool#38]
When I run the Filebot tool it tells me that Filebot is unregistered. I have paid for the software and activated it. It works fine when I run the desktop app, just not when I use the plugin. The error is below. Any help would be appreciated. 

> FilebotRuntimeError error on torrent 056c500947f119604488b6658293e3e796bc37c2:
>     FILEBOT OUTPUT DUMP:
>     License Error: UNREGISTERED

**Comment by rednoah** [comment]
Most likely because `deluge` is running as a different user, so that user will have a different `$HOME` folder and different app data folder / caches / etc, so you'll need to call `filebot --license` as the `deluge` user once as well.

**Comment by jako800** [comment]
Thanks for your response. I should've mentioned that I am using Deluge and Filebot on Windows 10, not Linux. I did not see anything about Windows support, does the tool work on Windows?

**Comment by rednoah** [comment]
I'm not sure if this plugin has some kind of debug button, the calling `filebot -script fn:sysenv` would give us lots of important information, such as who is running the script, and what app data folder is being used.

**Comment by Laharah** [comment]
I'm not sure if this plugin has some kind of debug button

It does not, but it can. I had no idea about that script. It'd come in handy often when trying to identifying these bugs. When I get home I can put in a debug button to bring up the call.

**Comment by rednoah** [comment]
`filebot -script fn:sysinfo` and `filebot -script fn:sysenv` or often useful for debugging.

**Comment by jako800** [comment]
Is there a way for me to run the script on Windows? Sorry, but I’m somewhat new at this.

**Comment by rednoah** [comment]
You can call it yourself by running CMD. But even if it works under your normal user, it still won't necessarily work under the user that deluge is running as.

**Comment by Laharah** [comment]
@jako800 I've added a debug info button in the [latest release](https://github.com/Laharah/deluge-FilebotTool/releases/latest). Download and install the new version, then click on the "Debug Info" button at the bottom of the preferences. If you copy and paste what it gives you here we can better help you figure out what's going on. 

It'd also be helpful if you also went into the command line (type "cmd" in the start menu) and gave us the result of typing `filebot -script fn:sysenv` and `filebot -script fn:sysinfo` to compare against.

**Comment by Laharah** [comment]
So it looks like you have 2 different userdata folders one at `C:\Users\BlackBox\AppData` and the other at `C:\Windows\System32\config\systemprofile\AppData`. And it looks like deluge is installed on one, while your default filebot is installed in the other. I'm not entirely sure how or why this happened, but deluge is running in the environment in the systemprofile one and your filebot license is in your user profile.

You have a couple options, you could re-install deluge and see if you can get it to use your normal profile instead of the system profile. (you should be able to copy and paste the deluge profile over the new install so you don't lose any torrents.) Or you could try and copy your license to the system profile. The license should be somewhere in `C:\Users\BlackBox\AppData\Roaming\FileBot` and you should be able to place it in `C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\FileBot`

**Comment by Laharah** [comment]
Well, it was fairly straight forward to implement after some tempfile jiggery to allow a license file to be uploaded to the server and activated with FileBot.

@jako800 
[The new release](https://github.com/Laharah/deluge-FilebotTool/releases/latest) has a register button in the preferences that will let you choose your license file and activate FileBot directly, which means you won't have to mess around with linking or copying or anything like that. Let me know if it works for you.

Thanks @rednoah for your help!

**Comment by rednoah** [comment]
Yep, that's probably the best solution. That's what I'm doing with `FileBot Node` as well.

**Comment by jako800** [comment]
Sorry for the delay in my reply. I very much appreciate the time you have put into the problem for me.

I have used the new register button in your new release, but nothing seemed to change. It still does not work and tells me that FileBot is unregistered. I tested the license file by reactivating the FileBot software and it worked as expected.

FileBot Tool debug output and error message attached.

**FileBot Error.**

> FilebotRuntimeError error on torrent f6220b96926dd02ef215d8724fe1d24e5b937391:
>     FILEBOT OUTPUT DUMP:
>     Rename episodes using [AniDB]
>     Auto-detected query: [Sword Art Online Alicization, sword art online]
>     Fetching episode data for [Sword Art Online: Alicization]
>     Fetching episode data for [Sword Art Online II]
>     Fetching episode data for [Sword Art Online]
>     Fetching episode data for [Sword Art Online: Extra Edition]
>     Fetching episode data for [Gekijouban Sword Art Online: Ordinal Scale]
>     Resource not found: https://api.thetvdb.com/search/series?name=Sword+Art+Online+Alicization
>     License Error: UNREGISTERED
>      ________________________________________________ 
>     / Please purchase a FileBot License:             \
>     \ https://www.filebot.net/purchase.html#msi      /
>      ------------------------------------------------ 
> psm` install your FileBot license.
>     
>     stderr:
>     Resource not found: https://api.thetvdb.com/search/series?name=Sword+Art+Online+Alicization
>     License Error: UNREGISTERED
>     FileBot requires a valid license. Please run `filebot --license *.psm` install your FileBot license.
> 


**Here is the debug output.**

> FileBot
> 
>  4.8.2 (r5789)
> 
> JNA Native: 5.2.2
> 
> MediaInfo: 18.05
> 
> 7-Zip-JBinding: 9.20
> 
> Chromaprint: 1.4.2
> 
> Extended Attributes: OK
> 
> Unicode Filesystem: OK
> 
> Script Bundle: 2019-01-16 (r540)
> 
> Groovy: 2.5.1
> 
> JRE: Java(TM) SE Runtime Environment 10.0.2
> 
> JVM: 64-bit Java HotSpot(TM) 64-Bit Server VM
> 
> CPU/MEM: 2 Core / 996 MB Max Memory / 33 MB Used Memory
> 
> OS: Windows 10 (amd64)
> 
> Package: MSI
> 
> License: UNREGISTERED
> 
> Done ?(?????)?
> 
> # Environment Variables #
> 
> LOCALAPPDATA: C:\WINDOWS\system32\config\systemprofile\AppData\Local
> 
> PROCESSOR_LEVEL: 6
> 
> USERDOMAIN: WORKGROUP
> 
> ALLUSERSPROFILE: C:\ProgramData
> 
> PROCESSOR_ARCHITECTURE: AMD64
> 
> PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
> 
> SystemDrive: C:
> 
> APPDATA: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming
> 
> USERNAME: BLACKBOX$
> 
> ProgramFiles(x86): C:\Program Files (x86)
> 
> CommonProgramFiles: C:\Program Files\Common Files
> 
> Path: C:\Program Files (x86)\Deluge;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\FileBot\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\FileBot\jre\bin
> 
> PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
> 
> DriverData: C:\Windows\System32\Drivers\DriverData
> 
> OS: Windows_NT
> 
> COMPUTERNAME: BLACKBOX
> 
> PROCESSOR_REVISION: 3a09
> 
> CommonProgramW6432: C:\Program Files\Common Files
> 
> ComSpec: C:\WINDOWS\system32\cmd.exe
> 
> ProgramData: C:\ProgramData
> 
> ProgramW6432: C:\Program Files
> 
> SystemRoot: C:\WINDOWS
> 
> TEMP: C:\WINDOWS\TEMP
> 
> PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
> 
> USERPROFILE: C:\WINDOWS\system32\config\systemprofile
> 
> TMP: C:\WINDOWS\TEMP
> 
> CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
> 
> ProgramFiles: C:\Program Files
> 
> PUBLIC: C:\Users\Public
> 
> NUMBER_OF_PROCESSORS: 2
> 
> windir: C:\WINDOWS
> 
> 
> 
> 
> # Java System Properties #
> 
> sun.desktop: windows
> 
> awt.toolkit: sun.awt.windows.WToolkit
> 
> java.specification.version: 10
> 
> file.encoding.pkg: sun.io
> 
> sun.cpu.isalist: amd64
> 
> sun.jnu.encoding: Cp1252
> 
> java.class.path: C:\Program Files\FileBot\jar\filebot.jar
> 
> net.filebot.AcoustID.fpcalc: C:\Program Files\FileBot\lib\fpcalc.exe
> 
> sun.awt.enableExtraMouseButtons: true
> 
> java.vm.vendor: "Oracle Corporation"
> 
> grape.root: C:\Windows\System32\config\systemprofile\AppData\Roaming\FileBot\grape
> 
> useExtendedFileAttributes: true
> 
> sun.arch.data.model: 64
> 
> jna.library.path: C:\Program Files\FileBot\lib
> 
> user.variant: 
> 
> java.vendor.url: http://java.oracle.com/
> 
> user.timezone: 
> 
> jna.nounpack: true
> 
> os.name: Windows 10
> 
> java.vm.specification.version: 10
> 
> sun.net.client.defaultReadTimeout: 60000
> 
> jna.boot.library.path: C:\Program Files\FileBot\lib
> 
> sun.java.launcher: SUN_STANDARD
> 
> user.country: US
> 
> sun.boot.library.path: C:\Program Files\FileBot\jre\bin
> 
> sun.java.command: C:\Program Files\FileBot\jar\filebot.jar -script fn:sysenv
> 
> jdk.debug: release
> 
> sun.cpu.endian: little
> 
> user.home: C:\WINDOWS\system32\config\systemprofile
> 
> user.language: en
> 
> java.specification.vendor: Oracle Corporation
> 
> java.version.date: 2018-07-17
> 
> java.home: C:\Program Files\FileBot\jre
> 
> file.separator: \
> 
> java.vm.compressedOopsMode: 32-bit
> 
> line.separator: 
> 
> 
> 
> unixfs: false
> 
> useCreationDate: false
> 
> java.specification.name: Java Platform API Specification
> 
> java.vm.specification.vendor: Oracle Corporation
> 
> java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
> 
> useNativeShell: false
> 
> http.agent: FileBot/4.8.2
> 
> user.script: 
> 
> sun.management.compiler: HotSpot 64-Bit Tiered Compilers
> 
> java.runtime.version: 10.0.2+13
> 
> user.name: BLACKBOX$
> 
> sun.net.client.defaultConnectTimeout: 10000
> 
> path.separator: ;
> 
> java.net.useSystemProxies: true
> 
> application.help: show
> 
> os.version: 10.0
> 
> jna.nosys: true
> 
> java.runtime.name: Java(TM) SE Runtime Environment
> 
> file.encoding: Cp1252
> 
> jnidispatch.path: C:\Program Files\FileBot\lib\jnidispatch.dll
> 
> java.vm.name: Java HotSpot(TM) 64-Bit Server VM
> 
> java.vendor.version: 18.3
> 
> jna.loaded: true
> 
> java.vendor.url.bug: http://bugreport.java.com/bugreport/
> 
> java.io.tmpdir: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\FileBot\tmp
> 
> swing.crossplatformlaf: javax.swing.plaf.nimbus.NimbusLookAndFeel
> 
> java.version: 10.0.2
> 
> user.dir: C:\Program Files (x86)\Deluge
> 
> os.arch: amd64
> 
> java.vm.specification.name: Java Virtual Machine Specification
> 
> java.awt.printerjob: sun.awt.windows.WPrinterJob
> 
> sun.os.patch.level: 
> 
> application.deployment: msi
> 
> java.library.path: C:\Program Files\FileBot\lib
> 
> java.vendor: Oracle Corporation
> 
> java.vm.info: mixed mode
> 
> java.vm.version: 10.0.2+13
> 
> application.dir: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\FileBot
> 
> sun.io.unicode.encoding: UnicodeLittle
> 
> org.apache.commons.logging.Log: org.apache.commons.logging.impl.NoOpLog
> 
> java.class.version: 54.0
> 
> 
> 
> 
> # Arguments #
> 
> args[0] = -script
> 
> args[1] = fn:sysenv
> 
> 
> 
> 
> Done 
> 
>  ?(?????)?
> 
> 
>

**Comment by Laharah** [comment]
You should have gotten a message saying if the license registration succeeded or failed. Could you post logs of what happens when you try and register? 

Also make sure you are on filebottool version 1.2.5 as 1.2.4 had a windows bug in it.

**Comment by jako800** [comment]
Sorry, I thought I left a reply already.  The register button is working as expected now and the tool is registered. Thanks for all of your help and time.
