### ISSUE TITLE
Unable to match content via Filebottool

### ISSUE THREAD

**Issue by generiskk** [Laharah/deluge-FileBotTool#39]
When using the function: "Dry Run", it keeps "spinning", unable to find any files. 

Current settings: 
![image](https://user-images.githubusercontent.com/36735685/51433108-cbdaa000-1c43-11e9-9bca-37110aab2c65.png)

Anything that is recommended to do to make it work?

**Comment by generiskk** [comment]
Maybe a good idea for me to actually paste the log too. 


`[INFO    ] 00:16:25 daemon:127 Deluge daemon 1.3.15
[INFO    ] 00:16:25 core:87 Starting libtorrent 1.1.12.0 session..
[INFO    ] 00:16:25 rpcserver:369 Starting DelugeRPC server :60032
[WARNING ] 00:16:25 preferencesmanager:528 GeoIP Unavailable
[INFO    ] 00:16:25 pluginmanagerbase:158 Plugin ltConfig enabled..
[INFO    ] 00:16:25 core:96 [FileBotTool] Filebot Found with version FileBot 4.8.2 (r5789) / Java(TM) SE Runtime Environment 10.0.2 / Linux 4.15.0-43-generic (amd64)
[INFO    ] 00:16:25 pluginmanagerbase:158 Plugin FileBotTool enabled..
[INFO    ] 00:16:25 torrentmanager:651 Successfully loaded state file: /home/gen/.config/deluge/state/torrents.state
[INFO    ] 00:16:25 torrentmanager:780 Successfully loaded fastresume file: /home/gen/.config/deluge/state/torrents.fastresume
[INFO    ] 00:16:25 torrentmanager:540 Torrent Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb added by user:
[INFO    ] 00:16:31 rpcserver:206 Deluge Client connection made from: 192.168.10.195:61521
[INFO    ] 00:16:31 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 00:16:33 rpcserver:206 Deluge Client connection made from: 192.168.10.195:61523
[INFO    ] 00:16:35 core:213 [FileBotTool] No movements for fe18d55d01030ddb11b1301dc940c0cd38334eff
[ERROR   ] 00:16:39 core:234 [FileBotTool] could not find index for /media/6TB/torrents/data/Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb/Brooklyn.Nine-Nine.S06E02.Hitchcock.and.Scully.1080p.AMZN.WEB$ZN.WEB-DL.DDP5.1.H.264-NTb.mkv in the torrent, problem with movement matching.


`

**Comment by Laharah** [comment]
Thanks for the log. It makes figuring out what's wrong way easier. It looks like your save path got a trailing '/' along the way (those are supposed to be cleaned along the way) It caused the plugin to search for a file with a path at `.../torrents/data//Brooklyn...` instead of `.../torrents/data/Brooklyn...`. The plugin has to do a lot of path munging and processing to get everything in the right format and os style and had a bug with those trailing slashes.

I added a patch with 66b8436 so the [latest release](https://github.com/Laharah/deluge-FilebotTool/releases/latest) should fix the issue. If it doesn't, let me know and I can take another crack at it.

**Comment by generiskk** [comment]
Thank you, I was not aware that my pathing was wrong. Resolved that too just incase, however I am still stuck on "problem with movement matching" 
[deluge.log](https://github.com/Laharah/deluge-FileBotTool/files/2776450/deluge.log)

**Comment by Laharah** [comment]
Sorry about that. Long hours on the road made me mess up the code. 
This release: https://github.com/Laharah/deluge-FileBotTool/releases/tag/1.2.3  should have the proper fix.

**Comment by generiskk** [comment]
Works like a dream now! Thank you sir!
