### ISSUE TITLE
Pausing Torrents While Processing

### ISSUE THREAD

**Issue by niayh** [Laharah/deluge-FileBotTool#4]
Hey again

Been using the plugin flawlessly for a while now and haven't run into any significant bugs -- always recommending your work to those looking for filebot integration.

I am just working on setting up a fully automated solution with this plugin, but something preventing me from moving forward is how the torrent pauses during processing. I can see how this would be necessary if your are looking to copy or move the file as part of the process -- in order to make sure the file can be moved, we need to ensure that it is not currently being accessed by deluge (highly likely if a torrent JUST finished downloading). However, is this behavior necessary for torrents we request to be symlinked or hardlinked? I would like to not lose out on upload because the torrent paused immediately after download because after resuming other peers may already be finished downloading or simply not be reconnected again.

I understand if this may be too difficult to implement but would just like to throw it out there as a possibility.

Thanks!

**Comment by Laharah** [comment]
I suppose it's not strictly necessary in that situation. Should be a fairly easy change to implement; I'll look into it this weekend.

**Comment by Laharah** [comment]
Should be all set in the new release, thanks for the suggestion!

**Comment by niayh** [comment]
That was fast! Thanks a bunch
