### ISSUE TITLE
Incompatable with deluge 2.0

### ISSUE THREAD

**Issue by Laharah** [Laharah/deluge-FileBotTool#40]
As it is now, the plugin doesn't currently support deluge 2.0.

Updating the plugin is a priority, but will take some time as a few things are required:

* migrate code to python3
* double checking uincode/bytecode seperation
* gtk3 duplication
* move from libglade calls to gtk.builder

There are likely some edge cases the move to deluge 2.0 may have changed. I'm open pull requests for any of these issues, but I accept that the code may not be particularly collaborator friendly. 

I'm planning to start work once there are installers for deluge 2.0 on windows and on osx.

**Comment by GentleHoneyLover** [comment]
Is deluge 2.0 support still planned or is the plug-in officially abandoned? :) If latter, what are the alternatives for using filebot with deluge?

**Comment by Laharah** [comment]
yes, I'm still planning to update the plugin for 2.0, however there still doesn't seem to be any kind of official windows installer. As this is the second time I'm hearing about people wanting a 2.0 compatible version I think there may be enough demand that a separately maintained 2.0 branch is warranted.

I can't give any hard dates right now, but I should be able to begin work on it sometime next week.

**Comment by GentleHoneyLover** [comment]
Great! Your plug-in is what stops me from upgrading to deluge 2.0 ;)

I think a lot of people run deluge and fileboot on a headless Linux server. I recently put both in a Docker container. Settings that aren’t available on webui I control via a GUI client (either on a Mac or Ubuntu desktop).

**Comment by Laharah** [comment]
That's what I do as well, unfortunately, my plugin doesn't support the webui, and I access the gui from a mac and a windows gui. The 2.0 server doesn't support connections from the 1.0 client, so I'd have to figure out a way to install 2.0 on windows to use the client from my desktop, essentially dropping support for windows clients going forward.

**Comment by GentleHoneyLover** [comment]
Maybe that's an opportunity to introduce a web ui support :)

Thanks for the great software, btw! Have been a paid user for years! :)

**Comment by VladGrant** [comment]
I just want to add that I've also been quietly keeping an eye on this and is literally the only issue that keeps me from upgrading to Deluge 2.0 . I might need to take the docker approach as well soon since I think python 2 is about to stop getting maintained as a whole soon.

**Comment by Laharah** [comment]
So I've finally got a 2.0 version of the plugin working, sorry it took so long. 

You can download the first release here:
https://github.com/Laharah/deluge-FileBotTool/releases/tag/2.0.0

The plugin on the release page was compiled with python3.9. If your deluge2.0 runs on a different python version, you may have to rename the .egg file to the correct version or re-compile the plugin yourself which isn't too difficult. The instructions are on the readme but I'll copy them down below too. 

Please report any bugs you find when running the plugin, especially on deluge version 2.0 as my ability to test it for compatibility is somewhat limited.

-------
### How to build the plugin from source
You will need:
- git
- a version of python that matches the version of python deluge is running on

##### Instructions:
- in a command window, type
```
    git clone https://github.com/Laharah/deluge-FileBotTool.git
    cd deluge-FileBotTool
    git checkout master
```

- then to build the plugin, on linux/osx type:
```
    python3 setup.py bdist_egg
```
The compiled .egg file will then be located in the `dist` folder
