### ISSUE TITLE
Set up with portable FileBot

### ISSUE THREAD

**Issue by Cry0nicS** [Laharah/deluge-FileBotTool#41]
I have a portable version of FileBot. 

Is there any way I can make the tool work with this? Is there a way to specify the FileBot folder location?

**Comment by Cry0nicS** [comment]
Solved this myself: it works if FileBot is extracted in "C:\Program Files\Filebot" and Deluge is run as _Administrator_ (doesn't work otherwise).

**Comment by Laharah** [comment]
Unfortunately not at the moment. There is a list of locations that the plugin searches for filebot though: https://github.com/Laharah/deluge-FileBotTool/blob/67e76a0c0cd6e4f9f922d485c596c48c38f5a2c1/filebottool/pyfilebot.py#L21-L24

**Comment by rednoah** [comment]
Linking `filebot` into `/usr/bin/filebot` is generally recommended, especially if you're using the portable package:
https://github.com/filebot/plugins/blob/master/installer/tar.sh
