### ISSUE TITLE
filebottool.js Error

### ISSUE THREAD

**Issue by Linney** [Laharah/deluge-FileBotTool#45]
Hello,

I have a Raspberry Pi 4 B (4GB RAM) running an up-to-date version of Buster.

The RPi is running Deluge 1.3.6 as well as FileBot, PlexMediaServer.

Deluge has the FileBotTool plugin (with a valid 1 yr license) installed alongside Labels, AutoRemovePlus, and YaRSS2.

New torrents are downloaded to a USB HDD and then sorted by FileBotTool to a different directory on the same drive.

When I tried to connect to deluge via my browser I was met with this error message:
https://imgur.com/a/tSo27F6

As far as I can tell, a recent download has finished and FileBotTool crashed Deluge before sorting the newly completed torrent.

Usually FileBotTool works flawlessly but something similar to this has happened once before. Rebooting the RPi fixed the issue in both instances however I'm wondering if there is anything I can do to prevent this from happening again.

Any input is welcome. Thanks.

**Comment by Laharah** [comment]
I don't think that should be happening. But I went ahead and removed all the unused webui stuff anyways. Let me know if it happens again on the [new release](https://github.com/Laharah/deluge-FileBotTool/releases/tag/1.2.8).

**Comment by Linney** [comment]
Hey, thank you so much for the quick reply and for the update. 

I've now updated my version of FileBotTool and I will let you know if I run into any further issues.

Thanks again.
