### ISSUE TITLE
New Database TheMovieDB::Tv

### ISSUE THREAD

**Issue by Linney** [Laharah/deluge-FileBotTool#46]
Enhancement / Question

After spending some time on the Filebot forums, it seems like you are able to use the IMDb database but specify that you're only interested in TV show results by appending `--db TheMovieDB::TV` onto the CLI input.

Would it be possible to incorporate IMDb::TV into the FilebotTool database list?

Or is there a way to correctly pass in arguments such as `--db TheMovieDB::TV` when using FilebotTool?

Thank you.

**Comment by Laharah** [comment]
I've added TheMovieDB::TV database in the [newest release](https://github.com/Laharah/deluge-FileBotTool/releases/tag/1.2.10). Looking through the forums it doesn't look like the `::TV` flag is used on any other databases (IMDb isn't supported in filebot). 

If you use the tag on some other db, can you let me know and show me a working command line example?

Gonna close this for now, feel free to re-open if you want some other db tag.

**Comment by rednoah** [comment]
`TheMovieDB::TV` is a database identifier like any other. The `::TV` has no meaning, other than that `TheMovieDB` was already taken.

**Comment by Laharah** [comment]
@rednoah cool, that's what I thought.

**Comment by Linney** [comment]
Thanks again for such a quick reply and response.


Thank you for continuing the improve FilebotTool.
