### ISSUE TITLE
Can you tell me where can I see deluge's log files?

### ISSUE THREAD

**Issue by ma3252788** [Laharah/deluge-FileBotTool#49]
mac OS10.15.3

**Comment by Laharah** [comment]
Deluge doesn't keep log files by default, you have to run deluge with the `-l` option.  

On OSX you can run deluge with logs enabled by opening up a terminal and running this:

`/Applications/Deluge.app/Contents/MacOS/Deluge -L debug -l ~/Desktop/deluge.log`

Here the `-L` flag sets the log level to debug, meaning as many events as possible are logged (filebottool) does most of it's logging at this level) and `-l` tells deluge to write the log file to a file on the desktop called `deluge.log`.
