### ISSUE TITLE
Plugin Problem

### ISSUE THREAD

**Issue by Latinkidmj** [Laharah/deluge-FileBotTool#5]
Hello.  I'm having a problem.  [Here ](https://www.youtube.com/watch?v=0R2FoqXlctg&feature=youtu.be&hd=1)is the explanation. The expression that I'm using is this: {n}/{n} Season {s}/{n} S{s.pad(2)}E{e.pad(2)} - {t} and it should move the correctly renamed files and folder to D:\TV. Unfortunately, it seems to be doing the following:

It will move the **_original_** files and **_original_** folder to D:\TV as indicated in the video clip above. But it will also correctly create a properly renamed folder and files into the same location on D:\TV as indicated in the video clip above. Unfortunately it also adds an extra subfolder for some reason I've yet to comprehend. I do not need either the extra subfolder OR the original files and folders after the torrent is downloaded and correctly renamed and relocated to D:\TV.  Can you help?!

**Comment by Laharah** [comment]
I'll look into it in the morning. I'll have to see if there's an issue with
those specific names or something more general. At first glance, it looks
like a configuration error. can you force a recheck on the torrent to see
if the files were actually moved? If they have, you can safely delete the
originals, otherwise, try to use FileBot history and click the revert
button to make the torrent point to the originals.

Where we're the original files downloaded to?

**Comment by Latinkidmj** [comment]
They were moved and I was able to delete the originals without any problems...but I have almost a Terabyte of files waiting to be downloaded and hate to have to do this for the next 100 or 150 torrents...

M.

Sent from my iPad

On Jul 21, 2016, at 3:11 AM, Jared Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll look into it in the morning. I'll have to see if there's an issue with
those specific names or something more general. At first glance, it looks
like a configuration error. can you force a recheck on the torrent to see
if the files were actually moved? If they have, you can safely delete the
originals, otherwise, try to use FileBot history and click the revert
button to make the torrent point to the originals.

Where we're the original files downloaded to?

**Comment by Laharah** [comment]
Are all renames having this issue, or is this a one time occurrence?

**Comment by rednoah** [comment]
I'd be great if the plugin had any options for enabling debug logging so we can see the filebot command and the console output.

**Comment by Laharah** [comment]
It actually does log those things to the deluge logs, you'll have to run
deluge with the debug logging flag:

http://dev.deluge-torrent.org/wiki/Troubleshooting#WindowsSpecificLogging

**Comment by Latinkidmj** [comment]
They all are (now) but I don't know why or what happened to change things. I'm off to bed though it's almost 4am here on PST.

Sent from my iPad

On Jul 21, 2016, at 3:34 AM, Jared Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:

Are all renames having this issue, or is this a one time occurrence?

**Comment by rednoah** [comment]
Alright, then @Latinkidmj just has to run deluge with the debug logging flag and see what the filebot command/output says.

**Comment by Latinkidmj** [comment]
When I open the cli and type "%ProgramFiles%\Deluge\deluge-debug.exe" -L error -l "%UserProfile%\Desktop\deluge.log" I get an error message saying “System cannot find the path”?

**Comment by Latinkidmj** [comment]
When I run "%ProgramFiles%\Deluge\deluge-debug.exe" -L error -l "%UserProfile%\Desktop\deluge.log" from the command prompt, I get an error saying “The system cannot find the path”.  I’m assuming this is how one runs the filebot with logging enabled?

**Comment by Latinkidmj** [comment]
So I'm still at a loss as to how I should proceed?

**Comment by Laharah** [comment]
try opening cmd, navigating to the deluge folder, and running `deluge-debug.exe -L debug -l deluge.log`. Then run the rename and return the log here. 

I can't seem to replicate the bug, so until I have a log of it happening I can't do much but keep an eye out for what may have caused it.

**Comment by Latinkidmj** [comment]
I rant the commend that you specified and it appeared to work as Deluge was already open and seeding and came to the front of everything I had open on the desktop at the time.  However I didn’t SEE anything different?  How can I rename the file when I don’t know where it is much less attach it? A little clarification on this step would be helpful.

**Comment by Laharah** [comment]
You have to quit deluge and make sure it isn't running in your tray, then run the commands I gave you. Then once you've tried the rename and replicated the issue, send the new `deluge.log` file that should be in the deluge folder next to the deluge.exe

**Comment by Latinkidmj** [comment]
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Windows\System32>cd..

C:\Windows>cd..

C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is 063C-D240

 Directory of C:\

06/30/2016  11:06 PM    <DIR>          Intel
08/01/2016  05:29 AM    <DIR>          Movies
10/30/2015  12:24 AM    <DIR>          PerfLogs
08/01/2016  12:34 AM    <DIR>          Program Files
08/01/2016  01:31 AM    <DIR>          Program Files (x86)
02/29/2016  01:42 PM    <DIR>          Users
07/15/2016  05:17 PM    <DIR>          Windows
               0 File(s)              0 bytes
               7 Dir(s)  169,297,465,344 bytes free

C:\>cd Program Files (x86)

C:\Program Files (x86)>deluge-debug.exe -L debug -l deluge.log
'deluge-debug.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files (x86)>cd Deluge

C:\Program Files (x86)\Deluge>deluge-debug.exe -L debug -l deluge.log
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__deluge-debug__.py", line 9, in <module>
  File "deluge\main.py", line 96, in start_ui
  File "deluge\log.py", line 65, in setupLogger
  File "logging/__init__.py", line 1402, in basicConfig
  File "logging/__init__.py", line 827, in __init__
  File "logging/__init__.py", line 846, in _open
IOError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Deluge\\deluge.log'

C:\Program Files (x86)\Deluge>

**Comment by Latinkidmj** [comment]
I just ran the command that you gave me and listed above is the results. I'm afraid I can't find a "deluge.log" file anywhere on my system.

**Comment by Laharah** [comment]
it seems you don't have permission to write to the programfiles\deluge folder. You'll have to either run the cmd window as administrator, or put the path of a folder you can write to in front of deluge.log . 

ex: `deluge-debug.exe -L debug -l C:\Users\USERNAME\Desktop\deluge.log`

**Comment by Latinkidmj** [comment]
Well it appears that the plugin won't work at ALL now in Deluge :(  It just hangs while "thinking"...attached is the deluge.log file.
[deluge.docx](https://github.com/Laharah/deluge-FileBotTool/files/394844/deluge.docx)

**Comment by Latinkidmj** [comment]
UPDATE:  Filebot's Plugin appears to be working again.  I've since switched out a buggy hard drive and it's working now, albeit with a slight change to the original problem.  Everything has been renames and relocated EXCEPT the original file folder which refuses to be renamed while all Season Folders still appear renamed (folders that I don't kneed) and of course the files themselves are renamed perfectly as well.

So I STILL wish to get rid of the folders by season convention and just have one folder with the title of the series with ALL the .mkv files in it (also properly reneamed).  Can you help?

**Comment by Laharah** [comment]
if you press the `format expression` link in the rename window, it'll bring you to http://www.filebot.net/naming.html where you can get info about how to craft a format expression to your liking. Something like `{n}/{n} - {S00E00}` should work, just set output to where you want the show's folder saved to.

**Comment by Laharah** [comment]
I'm going to mark this as closed since it seems to have been a hardware error. Feel free to re-open if you can replicate the bug on the new drive.
