### ISSUE TITLE
FilebotTool installed but all info are "not available"

### ISSUE THREAD

**Issue by napopa** [Laharah/deluge-FileBotTool#51]
Hi, I installed the plugin on Deluge 2.0.3 using the python 3.9 version. The plugin appears in the list with the "Enabled" checkmark selected, but it does not appear in the plugin list and all the info are "not available". Anything I can do to fix this? Thanks 

![Screenshot from 2022-01-21 20-39-20](https://user-images.githubusercontent.com/1825236/150619787-b856fa24-9986-4a72-aef6-28263cec4624.png)

**Comment by Laharah** [comment]
Hi, are you sure you're using the same version of python for deluge that you downloaded the plugin for? You should be able to check by checking the about page in deluge.

If that's all in order the next step would be making sure that it's not a permissions issue. The user that's running deluge has to have read and write access to the deluge plugins folder. (In fact, I would double check that the `.egg` file is actually in there.)

Where that folder is depends on your operating system and where deluge was installed to. Assuming you're on mac/linux and you didn't do anything special while installing it, it should be in `~/.config/deluge/plugins`.

If all that is fine and restarting deluge doesn't work I'd need to see some debug logs from deluge when it starts up and tries to load the plugin.

**Comment by napopa** [comment]
It was indeed an error with the plugin file name, I changed to py3.10 and it's working now. Thanks
