### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by GentleHoneyLover** [Laharah/deluge-FileBotTool#56]
Hello,

Thanks for the great Deluge plugin! Has been working as a charm for me for many years!

I would like to report that when running the FileBotTool in a container with python 3.11 installed, the FileBotTool is unhappy with the `inspect` module (see screenshot with the error below). Rolling back to an older container base image (with python 3.10) "solves" the issue — the FileBotTool works as expected.

Google search on this gives a lot of results — here's [one](https://github.com/python/cpython/issues/100680#issuecomment-1368807709) that seems to explain the problem.

Any plans for releasing a new version that would support the latest python? Would be great for keeping the project alive and future-proof! ;)

<br><img width="843" alt="Screenshot 2023-11-08 at 14 10 18" src="https://github.com/Laharah/deluge-FileBotTool/assets/38346023/4d30ffd1-2daf-4355-a8f1-ae3ae6c37253"><br><br>

Output of the Debug Info:

```
FileBot 5.1.2 (r10125)
JNA Native: 6.1.6
MediaInfo: 23.07
Tools: fpcalc/1.5.1
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2023-11-06 (r952)
Groovy: 4.0.15
JRE: OpenJDK Runtime Environment 21.0.1
JVM: OpenJDK 64-Bit Server VM
FILEBOT_OPTS: -Dapplication.deployment=docker -Duser.home=/config/filebot
CPU/MEM: 8 Core / 2.1 GB Max Memory / 24 MB Used Memory
OS: Linux (aarch64)
HW: Linux 40161b5e6cd4 6.4.16-linuxkit #1 SMP PREEMPT Wed Oct 25 16:32:24 UTC 2023 aarch64 Linux
CPU/MEM: MemTotal: 8 GB / MemFree: 96 MB / MemAvailable: 7 GB / SwapTotal: 1.1 GB / SwapFree: 1.1 GB
STORAGE: overlay [/] @ 48 GB | ext4 [/data] @ 48 GB | fakeowner [/config] @ 581 GB | fakeowner [/downloads] @ 581 GB | ext4 [/watchfolder] @ 48 GB
UID/GID: uid=501(xyz) gid=65533(nogroup) groups=501(xyz),65533(nogroup),65533(nogroup)
DATA: /opt/filebot/data/501
Package: DOCKER
License: <redacted>
Done \u30fe(\uff20\u2312\u30fc\u2312\uff20)\u30ce

# Local Time #
Wed Nov 08 14:12:27 CET 2023

# Process Tree #
/usr/bin/python3.11
\u2514\u2500 /bin/busybox
   \u2514\u2500 /usr/lib/jvm/jdk-21.0.1-bellsoft-aarch64/bin/java

# Environment Variables #
BUILD_DATE: 7-Nov-2023
CONFIG: /config
DELUGE_CONFIG: /config/deluge
DELUGE_LOGLEVEL: info
FILEBOT_OPTS: -Dapplication.deployment=docker -Duser.home=/config/filebot
FILEBOT_PLUGIN_VERSION: 2.0.3-py3.9
HISTFILE: 
HOME: /config/filebot
HOSTNAME: 40161b5e6cd4
JAVA_HOME: /usr/lib/jvm/jdk-21.0.1-bellsoft-aarch64
LANG: en_US.UTF-8
LANGUAGE: en_US:en
LC_ALL: en_US.UTF-8
LD_LIBRARY_PATH: /usr/lib/jvm/jdk-21.0.1-bellsoft-aarch64/lib/server:/usr/lib/jvm/jdk-21.0.1-bellsoft-aarch64/lib:/usr/lib/jvm/jdk-21.0.1-bellsoft-aarch64/../lib
PATH: /usr/lib/jvm/jdk-21.0.1-bellsoft-aarch64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/filebot/lib/Linux-aarch64
PGID: 501
PUID: 501
PWD: /
PYTHON_EGG_CACHE: /config/deluge/plugins/.python-eggs
SHLVL: 2
SUPERVISOR_ENABLED: 1
SUPERVISOR_GROUP_NAME: deluged
SUPERVISOR_PROCESS_NAME: deluged
SUPERVISOR_SERVER_URL: unix:///run/supervisord.sock
```

**Comment by Laharah** [comment]
Thanks for the report! The new release should fix the issue.

LMK if either this fix doesn't work or if you run into a different issue. I don't currently have a 3.11 sever to test with but wanted to get this fix out quick :)

**Comment by GentleHoneyLover** [comment]
@Laharah, that was a lightning fast reaction — thanks! 

I updated my [alpine container image](https://github.com/GentleHoneyLover/deluge-filebot-docker/tree/alpine) and tested the new FileBotTool release. Everything seems to work as expected — no more python error.

Thanks a lot again!
