### ISSUE TITLE
[Question] Label Plus

### ISSUE THREAD

**Issue by saitoh183** [Laharah/deluge-FileBotTool#7]
Is it supported or is it only the default label system that is supported?

**Comment by Laharah** [comment]
I believe that both will work, However I'm not 100% sure. If you run into issues with it, let me know and I'll see if I can add explicit support.

**Comment by saitoh183** [comment]
Cool thanks... Just loving your plug-in... Saved me a hole lot of fiddling

**Comment by Laharah** [comment]
Glad to hear it's working well :)

**Comment by deepfriedmind** [comment]
I just tried it out and it would seem that auto-execution doesn't work with labels set via LabelPlus.

**Comment by Laharah** [comment]
I've added support for labelplus labels for auto-sorting. They take precedence over non-lableplus lables.

**Comment by deepfriedmind** [comment]
Wow, that was quick and it seems to be working well. Thanks! It also works with sub-labels if you use the `parent-label/sub-label` syntax for the pattern to match.
